name: build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: tuist clean
        run: tuist clean

      - name: tuist fetch
        run: tuist fetch

      - name: tuist generate -n
        run: tuist generate -n

      - name: run build
        run: tuist build --device "iPhone 14" --os 16.1

      # - name: run test
      #   run: tuist test --device "iPhone 14" --os 16.1

      - name: run test
        run: xcodebuild test \
          -workspace LifeBetter.xcworkspace \
          -scheme LifeBetter \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1'

      # See https://github.com/codecov/example-ci/blob/main/.github/workflows/ci.yml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
